<script lang="ts">
  import { goto } from "$app/navigation";
  import {
    type InsertPlant,
    type PlantWithDate,
    type SelectPlant
  } from "../../../lib/types";
  import { onDestroy, onMount } from "svelte";
  import { DateTime } from "luxon";

  import PlantDisplay from "$lib/shared-components/PlantDisplay.svelte";
  import PopupInfo from "./PopupInfo.svelte";

  import { invalidateAll } from "$app/navigation";
  import { decode, InputPlug, TetherAgent } from "tether-agent";
  import { BROWSER_CONNECTION } from "../../../defaults/tether";
  import {
    type EventNewSprouting,
    type EventPlantGenerated
  } from "$lib/events.types";
  import {
    DURATION_TILL_FERTILE,
    MAX_CANVASSES,
    PLUG_NAMES
  } from "$lib/constants";
  import PlantWasAddedPopup from "./PlantWasAddedPopup.svelte";
  import ConfirmBreedPopup from "./pollinate/[parent1id]/ConfirmBreedPopup.svelte";
  import { candidateToPlant } from "./pollinate/[parent1id]/PollinationFrontendFunctions";

  export let data;
  type GalleryViewData = typeof data;

  let candidateChild: InsertPlant | null = null;
  let selectedPlant: SelectPlant | null = null;

  let agent: TetherAgent | null;

  let newPlantForPopup: InsertPlant | null = null;

  onMount(async () => {
    // datesInterval = setInterval(updateTimeLeft, 1000);
    // const databaseInterval = setInterval(fetchdata, 1000);

    agent = await TetherAgent.create("app", {
      brokerOptions: BROWSER_CONNECTION
    });

    const newPlantAddedPlug = await InputPlug.create(
      agent,
      PLUG_NAMES.simpleEvents,
      {
        id: "newPlantPollination"
      }
    );
    newPlantAddedPlug.on("message", (payload) => {
      const m = decode(payload) as EventNewSprouting;
      if (
        m.payload.authorTop === data.user.id ||
        m.payload.authorBottom === data.user.id
      ) {
        console.log("This plant belongs to me!", m.payload);
        newPlantForPopup = m.payload;

        setTimeout(() => {
          console.log("Now clear popup...");
          newPlantForPopup = null;
          invalidateAll();
        }, 4000);
      }
      // For any "newPlantPollination" event, reload page data just in case
    });

    const newPlantGeneratedPlug = await InputPlug.create(
      agent,
      PLUG_NAMES.simpleEvents,
      {
        id: "newGeneratedPlantReady"
      }
    );
    newPlantGeneratedPlug.on("message", (payload) => {
      const m = decode(payload) as EventPlantGenerated;
      if (m.payload.authorTop === data.user.id) {
        console.log("This plant was generated by me!", m.payload);
        const { plantId, authorTop, authorBottom, imageUrl } = m.payload;
        candidateToPlant(plantId, authorTop, authorBottom)
          .then((p) => {
            console.log("Update candidate child with:", {
              plantId,
              authorTop,
              authorBottom
            });
            candidateChild = {
              ...p,
              imageUrl,
              authorTop,
              authorBottom
            };
          })
          .catch((e) => {
            console.error("Error from updating candidate child", e);
            candidateChild = null;
          });
      }
    });
  });

  onDestroy(() => {
    // if (datesInterval) {
    //   clearInterval(datesInterval);
    // }
    if (agent) {
      agent.disconnect();
    }
  });

  const gotoPollinate = (plantId: string) => {
    goto(`/app/gallery/scan/${plantId}`);
  };
</script>

{#if newPlantForPopup}
  <PlantWasAddedPopup plant={newPlantForPopup} />
{/if}

<div class="mt-16 mx-10 font-primer text-roel_blue text-left">
  <PlantDisplay
    disableAnimation={false}
    imageUrl={data.myOriginalPlant.plant.imageUrl || ""}
    applyFilters={false}
    label={data.myOriginalPlant.plant.commonName}
  />

  {#each data.myOtherPlants as plant, index}
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <!-- <code>{plant.plant.timeLeft.toFormat("mm:ss")}</code> -->
    <div
      on:click={() => {
        console.log("click!");
        selectedPlant = plant.plant;
      }}
      class="cursor-pointer mt-4 border-2 border-orange-50"
    >
      <PlantDisplay
        disableAnimation={index > MAX_CANVASSES - 1}
        imageUrl={plant.plant.imageUrl || ""}
        applyFilters={false}
        label={plant.plant.commonName}
      />
    </div>
    <div class="mt-4 text-center">Title</div>
  {/each}

  {#each data.notSproutedPlants as plant}
    <PlantDisplay
      disableAnimation={true}
      imageUrl={"/pollination/Seed_01.png"}
      applyFilters={false}
      label={"New plant"}
    />
  {/each}
</div>

{#if selectedPlant}
  <PopupInfo
    plantDetails={selectedPlant}
    closePopup={() => {
      selectedPlant = null;
    }}
  ></PopupInfo>
{/if}

{#if candidateChild}
  <ConfirmBreedPopup
    {candidateChild}
    onCancel={() => {
      candidateChild = null;
    }}
    onConfirm={() => {
      candidateChild = null;
      invalidateAll();
    }}
  />
{/if}

<div class="fixed bottom-0 w-screen content-center">
  <button
    on:click={() => gotoPollinate(data.myOriginalPlant.plant.id)}
    data-test="start-pollinating-button"
    data-umami-event="Start Pollinating Button"
    class="bg-roel_blue text-roel_green font-primer text-3xl px-4 py-[0.5rem] mb-5 border-2 w-11/12 max-w-xs border-roel_blue rounded-full active:bg-roel_blue active:text-roel_green"
  >
    Start Pollinating
  </button>
</div>

<!-- <div>{JSON.stringify(candidateChild)}</div> -->
